### ISSUE TITLE
微博授权登录返回的 User 的性别判断错误

### ISSUE THREAD

**Issue by keepcleargas** [suninformation/ymate-module-oauth-connector#1]
[WeiboConnectProcessor.java](https://raw.githubusercontent.com/suninformation/ymate-module-oauth-connector/master/src/main/java/net/ymate/module/oauth/connector/impl/WeiboConnectProcessor.java)
```java
               if (StringUtils.equals(_gender, "m")) {
                        _connectUser.setGender(OAuthConnectUser.Gender.FAMALE);
                    } else if (StringUtils.equals(_gender, "f")) {
                        _connectUser.setGender(OAuthConnectUser.Gender.MALE);
                    }
```

`FAMALE` -> `Female` 书写错误.

f -> `FAMALE `
m-> `MALE`

**Comment by suninformation** [comment]
@keepcleargas 已修改 :)
